---
- hosts: localhost
  gather_facts: false

  tasks:
    - import_tasks: tasks/debug1.yml
      when: debug1|d(false)|bool

    - import_tasks: tasks/debug2.yml
      when: debug2|d(false)|bool

    - import_tasks: tasks/debug3.yml

  handlers:
    - import_tasks: handlers/my_handler.yml

# shell> ansible-playbook pb3.yml -e debug2=true | grep msg:
#   msg: task 2
#   msg: task 3
#   msg: handler

- hosts: localhost
  gather_facts: false

  tasks:
    - import_tasks: tasks/debug1.yml
      when: debug1|d(false)|bool

    - import_tasks: tasks/debug2.yml
      when: debug2|d(false)|bool

    - meta: flush_handlers

    - import_tasks: tasks/debug3.yml

  handlers:
    - import_tasks: handlers/my_handler.yml

#   msg: task 2
#   msg: handler
#   msg: task 3
