- hosts: localhost

  vars:

    deploy_env:
      dev:
        schemas:
          year1: [main, custom]
          year2: [main, custom, security]
          year3: [main, custom]

  tasks:

    - set_fact:
        years: "{{ deploy_env.dev.schemas.keys() | list }}"
    - debug:
        var: item
      loop: "{{ years }}"

    - debug:
        msg: "{{ deploy_env.dev.schemas | difference(['year2']) }}"

# ok: [localhost] => (item=year1) => 
#   ansible_loop_var: item
#   item: year1
# ok: [localhost] => (item=year2) => 
#   ansible_loop_var: item
#   item: year2
# ok: [localhost] => (item=year3) => 
#   ansible_loop_var: item
#   item: year3

# msg:
#   - year3
#   - year1
