- hosts: localhost
  gather_facts: false
  tasks:
    - lineinfile:
        path: files/test.conf
        regexp: '^line4$'
        line: |
          pre-line4
          line4
          post-line4

# --- before: files/test.conf (content)
# +++ after: files/test.conf (content)
# @@ -1,5 +1,7 @@
#  line1
#  line2
#  line3
# +pre-line4
#  line4
# +post-line4
#  line5
