---
- name: 1.keep_keys
  block:
    - name: 1.Test keep_keys debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 1.Test keep_keys assert
      assert:
        that: result == target
  vars:
    result: "{{ l1|ansible.utils.keep_keys(target=['p1', 'p2']) }}"
    target:
      - { p1: a, p2: a }
      - { p1: b, p2: b }
      - { p1: c, p2: c }
  tags: keep_keys

- name: 2.map keep_keys
  block:
    - name: 2.Test map keep_keys debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 2.Test map keep_keys assert
      assert:
        that: result == target
  vars:
    result: "{{ l2|map('ansible.utils.keep_keys', target=['p1', 'p2'])|
      list }}"
    target:
      - - { p1: a, p2: a }
        - { p1: b, p2: b }
        - { p1: c, p2: c }
      - - { p1: a, p2: a }
        - { p1: b, p2: b }
        - { p1: c, p2: c }
      - - { p1: a, p2: a }
        - { p1: b, p2: b }
        - { p1: c, p2: c }
  tags: map_keep_keys

- name: 3.keep_keys starts_with
  block:
    - name: 3.Test keep_keys starts_with debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 3.Test keep_keys starts_with assert
      assert:
        that: result == target
  vars:
    result: "{{ l1|ansible.utils.keep_keys(target=['p1', 'p2'],
      matching_parameter= 'starts_with') }}"
    target:
      - { p1: a, p2: a }
      - { p1: b, p2: b }
      - { p1: c, p2: c }
  tags: keep_keys_starts_with_2

- name: 4.keep_keys starts_with 'p'
  block:
    - name: 4.Test keep_keys starts_with 'p' debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 4.Test keep_keys starts_with 'p' assert
      assert:
        that: result == target
  vars:
    result: "{{ l1|ansible.utils.keep_keys(target=['p'],
      matching_parameter= 'starts_with') }}"
    target:
      - { p1: a, p2: a, p3: a }
      - { p1: b, p2: b, p3: b }
      - { p1: c, p2: c, p3: c }
  tags: keep_keys_starts_with_1

- name: 5.keep_keys ends_with
  block:
    - name: 5.Test keep_keys end_with debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 5.Test keep_keys end_with assert
      assert:
        that: result == target
  vars:
    result: "{{ l1|ansible.utils.keep_keys(target=['p1', 'p2'],
      matching_parameter= 'ends_with') }}"
    target:
      - { p1: a, p2: a }
      - { p1: b, p2: b }
      - { p1: c, p2: c }
  tags: keep_keys_ends_with_2

- name: 6.keep_keys ends_with '2'
  block:
    - name: 6.Test keep_keys end_with '2' debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 6.Test keep_keys end_with '2' assert
      assert:
        that: result == target
  vars:
    result: "{{ l1|ansible.utils.keep_keys(target=['2'],
      matching_parameter= 'ends_with') }}"
    target:
      - { p2: a }
      - { p2: b }
      - { p2: c }
  tags: keep_keys_ends_with_1

- name: 7.keep_keys regex
  block:
    - name: 7.Test keep_keys regex debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 7.Test keep_keys regex assert
      assert:
        that: result == target
  vars:
    result: "{{ l1|ansible.utils.keep_keys(target=['p1', 'p2'],
      matching_parameter= 'regex') }}"
    target:
      - { p1: a, p2: a }
      - { p1: b, p2: b }
      - { p1: c, p2: c }
  tags: keep_keys_regex
