- hosts: localhost

  vars:

    l:
      - {k0_x0: A0, k1_x1: B0, k2_x2: [C0], k3_x3: foo}
      - {k0_x0: A1, k1_x1: B1, k2_x2: [C1], k3_x3: bar}
    mp: regex
    t: ['^.*[01]_x.*$']
    r: "{{ l | community.general.keep_keys(target=t, matching_parameter=mp) }}"

  tasks:

    - debug:
        var: r | to_yaml

#  r:
#    - {k0_x0: A0, k1_x1: B0}
#    - {k0_x0: A1, k1_x1: B1}
