- hosts: localhost

  vars:

    l:
      - {k0_x0: A0, k1_x1: B0, k2_x2: [C0], k3_x3: foo}
      - {k0_x0: A1, k1_x1: B1, k2_x2: [C1], k3_x3: bar}
    t: [k0_x0, k1_x1]
    r: "{{ l | community.general.keep_keys(target=t) }}"

  tasks:

    - debug:
        var: r | to_yaml
