---

- hosts: localhost

  tasks:

    - name: Return the intersection of list1 and list2.
      ansible.builtin.debug:
        var: result|to_yaml
      vars:
        list1: [1, 2, 5, 3, 4, 10]
        list2: [1, 2, 3, 4, 5, 11, 99]
        result: "{{ list1 | community.general.lists_intersect(list2) }}"
      # => [1, 2, 5, 3, 4]

    - name: Return the intersection of list1, list2 and list3.
      ansible.builtin.debug:
        var: result|to_yaml
      vars:
        list1: [1, 2, 5, 3, 4, 10]
        list2: [1, 2, 3, 4, 5, 11, 99]
        list3: [1, 2, 3, 4, 5, 10, 99, 101]
        result: "{{ [list1, list2, list3] | community.general.lists_intersect(flatten=true) }}"
      # => [1, 2, 5, 3, 4]

# EOF
...
