- name: Update my_cache_all
  set_fact:
    my_cache_all: "{{ my_cache_all|
                      combine({item: hostvars[item].my_cache}) }}"
  loop: "{{ ansible_play_hosts }}"
  run_once: true

- name: Write my_cache_all
  copy:
    dest: "{{ cache }}"
    content: |
      my_cache_all:
        {{ my_cache_all|to_nice_yaml|indent(2) }}
  run_once: true
  delegate_to: localhost
