- name: Sanity job. Run pgrep
  block:
    - name: Sanity job. Run pgrep
      command: "pgrep -f {{ bin_path }}/{{ my_script }}"
      register: sanity_job_result
      failed_when: sanity_job_result.rc > 1
      changed_when: false
    - name: Display sanity_job_result
      debug:
        var: sanity_job_result
      when: debug|d(false)|bool
    - name: Sanity job. Set job_exists and job_pid
      set_fact:
        job_exists: "{{ (sanity_job_result.rc == 0)|ternary(true, false) }}"
        job_pid: "{{ (sanity_job_result.rc == 0)|ternary(sanity_job_result.stdout, 'undef') }}"
  rescue:
    - name: Display ansible_failed_result
      debug:
        var: ansible_failed_result
      when: debug|d(false)|bool
    - name: End host
      meta: end_host
- name: Sanity job. PID file stat
  block:
    - name: Sanity job. PID file stat
      stat:
        path: "{{ pid_path }}/{{ my_pid }}"
      register: sanity_file_result
    - name: Display sanity_file_result
      debug:
        var: sanity_file_result
      when: debug|d(false)|bool
    - name: Sanity job. Set file_exists and file_pid
      set_fact:
        file_exists: "{{ sanity_file_result.stat.exists }}"
        file_pid: 'undef'
    - name: Sanity job. Read PID file
      command: "cat {{ pid_path }}/{{ my_pid }}"
      register: file_pid_result
      when: file_exists
    - name: Display file_pid_result
      debug:
        var: file_pid_result
      when: debug|d(false)|bool
    - name: Sanity job. Set file_pid
      set_fact:
        file_pid: "{{ file_pid_result.stdout }}"
      when: file_exists

- name: Display variables
  debug:
    msg: |-
      job_exists: {{ job_exists }}
      job_pid: {{ job_pid }}
      file_exists: {{ file_exists }}
      file_pid: {{ file_pid }}
  when: debug|d(false)|bool

- name: Sanity job. Assert PID file exists.
  block:
    - name: Sanity job. Assert PID file exists. Job exists.
      assert:
        that: job_exists
        fail_msg: >-
          [ERR] PID file { pid_path }}/{{ my_pid }} exists but
          job {{ bin_path }}/{{ my_script }} is not running.
    - name: Sanity job. Assert PID file exists. job PID match.
      assert:
        that: file_pid == job_pid
        fail_msg: >-
          [ERR] PID in file {{ file_pid  }} job PID {{ job_pid }} mismatch.
  when: file_exists

- name: Sanity job. Assert PID file not exist. Job not exist.
  assert:
    that: not job_exists
    fail_msg: >-
      [ERR] PID file { pid_path }}/{{ my_pid }} does not exist but
      job {{ bin_path }}/{{ my_script }} is running.
  when: not file_exists
