- name: Stop job
  block:
    - name: Stop job. PID read.
      command:
        cmd: "cat {{ pid_path }}/{{ my_pid }}"
        removes: "{{ pid_path }}/{{ my_pid }}"
      register: stop_job_pid
      changed_when: false
    - name: Stop job. Set job_pid
      set_fact:
        job_pid: "{{ stop_job_pid.stdout }}"
    - name: Stop job
      command:
        cmd: "kill -{{ signal }} {{ job_pid }}"
        removes: "{{ pid_path }}/{{ my_pid }}"
      register: stop_job_result
      notify: stop job
    - name: Stop job. Set stop_msg
      set_fact:
        stop_msg: '[SIG{{ signal }}] rc: {{ stop_job_pid.rc }}'
  rescue:
    - name: Display ansible_failed_result
      debug:
        var: ansible_failed_result
      when: debug|d(false)|bool
    - name: End host
      meta: end_host
  always:
    - name: Display stop_job_result
      debug:
        var: stop_job_result
      when: debug|d(false)|bool
