---

- hosts: localhost

  tasks:

    - ansible.builtin.debug:
        var: result|to_yaml
      vars:
        list1: [1, 2, 3, 4, 10]
        list2: [1, 2]
        result: "{{ list1 | community.general.lists_difference(list2) }}"
      # [3, 4, 10]

    - ansible.builtin.debug:
        var: result|to_yaml
      vars:
        list1: [1, 2, 3, 4, 10]
        list2: [1, 2]
        result: "{{ [list1, list2] | community.general.lists_difference() }}"
      # - [1, 2, 3, 4, 10]
      # - [1, 2]

    - ansible.builtin.debug:
        var: result|to_yaml
      vars:
        list1: [1, 2, 3, 4, 10]
        list2: [1, 2]
        result: "{{ [list1, list2] | community.general.lists_difference(flatten=true) }}"
      # [3, 4, 10]

    - ansible.builtin.debug:
        var: result|to_yaml
      vars:
        list1: [1, 2, 3, 4, 10]
        list2: [1, 2]
        list3: [3, 4]
        result: "{{ [list1, list2, list3] | community.general.lists_difference(flatten=true) }}"
      # [10]

    - name: Return the difference of list1 and list2.
      ansible.builtin.debug:
        msg: "{{ list1 | community.general.lists_difference(list2) }}"
      vars:
        list1: [1, 2, 5, 3, 4, 10]
        list2: [1, 2, 3, 4, 5, 11, 99]

    - name: Return the difference of list1, list2 and list3.
      ansible.builtin.debug:
        msg: "{{ [list1, list2, list3] | community.general.lists_difference(flatten=true) }}"
      vars:
        list1: [1, 2, 5, 3, 4, 10]
        list2: [1, 2, 3, 4, 5, 11, 99]
        list3: [1, 2, 3, 4, 5, 10, 99, 101]

# EOF
...
