---
- name: UBUNTU20-CIS | Test integration target parse_etc_password
  hosts: localhost
  gather_facts: true
  become: true

  # Test integration
  # shell> ANSIBLE_ROLES_PATH=/scratch/vbotka.UBUNTU20-CIS/tests/integration/targets

  roles:
    - role: parse_etc_password
