- name: Stop job. 91. Update record in my_cache.
  set_fact:
    my_cache: "{{ my_cache|combine(my_record, recursive=False) }}"
  vars:
    my_record: "{{ {my_script: {'running': false}} }}"
  listen: stop job

- name: Stop job. 92. Update my_cache_all
  set_fact:
    my_cache_all: "{{ my_cache_all|
                      combine({item: hostvars[item].my_cache}) }}"
  loop: "{{ ansible_play_hosts }}"
  run_once: true
  listen: stop job

- name: Stop job. 93. Write my_cache_all
  copy:
    dest: "{{ cache }}"
    content: |
      my_cache_all:
        {{ my_cache_all|to_nice_yaml|indent(2) }}
  run_once: true
  delegate_to: localhost
  listen: stop job
