- name: Test replace keys
  ansible.builtin.assert:
    that:
      - (rr | difference(item.result) | length) == 0
    success_msg: |
      [OK]  {{ item.label }}
      result:
        {{ rr | to_nice_yaml(indent=2) | indent(2) }}
    fail_msg: |
      [ERR] {{ item.label }}
      result:
        {{ rr | to_nice_yaml(indent=2) | indent(2) }}
    quiet: "{{ quiet_test | d(true) | bool }}"
  vars:
    rr: "{{ item.data |
            my_replace_keys(target=item.target,
                            matching_parameter=item.match) }}"
