- name: Test plugins/filter/replace_keys.py
  hosts: localhost

  vars:

    # ansible.utils.replace_keys - - - - - - - - - - - - - - - - - - - - - - - - -

    t:
      - {before: k0, after: a0}
      - {before: k1, after: a1}

    l1:
      - {k0: A, k1: B, k2: [""], k3: foo}
      - {k0: C, k1: D, k2: [""], k3: bar}
    r1: "{{ l1 | ansible.utils.replace_keys(target=t) }}"

    l9:
      - {k0: A, k1: B, k2: [X], k3: foo}
      - {k0: C, k1: D, k2: [Y], k3: bar}
    r9: "{{ l9 | ansible.utils.replace_keys(target=t) }}"

    l2:
      - {k0: A, k1: B, k2: C, k3: foo}
      - {k0: C, k1: D, k2: C, k3: bar}
    r2: "{{ l2 | ansible.utils.replace_keys(target=t) }}"

    # my_replace_keys - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    l3:
      - {k0_x0: A0, k1_x1: B0, k2_x2: [C0], k3_x3: foo}
      - {k0_x0: A1, k1_x1: B1, k2_x2: [C1], k3_x3: bar}

    tq:
      - {before: k0_x0, after: a0}
      - {before: k1_x1, after: a1}
    rq: "{{ l3 | my_replace_keys(target=tq) }}"

    ts:
      - {before: k0, after: a0}
      - {before: k1, after: a1}
    rs: "{{ l3 | my_replace_keys(target=ts, matching_parameter='starts_with') }}"

    te:
      - {before: x0, after: a0}
      - {before: x1, after: a1}
    re: "{{ l3 | my_replace_keys(target=te, matching_parameter='ends_with') }}"

    tl:
      - {before: "^.*0_x.*$", after: a0}
      - {before: "^.*1_x.*$", after: a1}
    rl: "{{ l3 | my_replace_keys(target=tl, matching_parameter='regex') }}"

    tx:
      - {before: "^.*_x.*$", after: X}
    rx: "{{ l3 | my_replace_keys(target=tx, matching_parameter='regex') }}"

    ty:
      - {before: "^.*_x.*$", after: X}
      - {before: "^.*_x.*$", after: Y}
    ry: "{{ l3 | my_replace_keys(target=ty, matching_parameter='regex') }}"

    l100:
      - {aaa1: A, bbb1: B, ccc1: C}
      - {aaa2: D, bbb2: E, ccc2: F}
    t100:
      - {before: a, after: X}
      - {before: aa, after: Y}
    r100: "{{ l100 | my_replace_keys(target=t100, matching_parameter='starts_with') }}"

  tasks:

    - debug:
        var: r1 | to_yaml
      tags: r1
      
    - debug:
        var: r2 | to_yaml
      tags: r2

    - debug:
        var: r9 | to_yaml
      tags: r9

    - debug:
        var: rq
      tags: rq

    - debug:
        var: rs
      tags: rs

    - debug:
        var: re
      tags: re

    - debug:
        var: rl
      tags: rl

    - debug:
        var: rx
      tags: rx

    - debug:
        var: ry
      tags: ry

    - debug:
        var: r100 | to_yaml
      tags: r100
