- hosts: localhost

  vars:

    firewall_rules:
      json:
        count: 2
        results:
        - action: pass
          created: '2024-06-20T09:53:20'
          destination_services:
          - {created: '2024-06-18T02:00:00', id: A}
          - {created: '2024-06-18T02:00:00', id: B}
        - action: deny
          created: '2024-06-20T09:53:20'
          destination_services:
          - {created: '2024-06-18T02:00:00', id: C}
          - {created: '2024-06-18T02:00:00', id: D}

    fpr_query: '[].{key: action, value: destination_services}'
    fpr: "{{ firewall_rules.json.results | json_query(fpr_query) }}"

    fp2_query: '[].[action, destination_services]'
    fp2: "{{ dict(firewall_rules.json.results | json_query(fp2_query)) }}"

  tasks:

    - debug:
        var: fpr | to_yaml

# fpr:
#   - key: pass
#     value:
#     - {created: '2024-06-18T02:00:00', id: A}
#     - {created: '2024-06-18T02:00:00', id: B}
#   - key: deny
#     value:
#     - {created: '2024-06-18T02:00:00', id: C}
#     - {created: '2024-06-18T02:00:00', id: D}

    - debug:
        var: fpr | items2dict | to_yaml

# fpr | items2dict:
#   deny:
#   - {created: '2024-06-18T02:00:00', id: C}
#   - {created: '2024-06-18T02:00:00', id: D}
#   pass:
#   - {created: '2024-06-18T02:00:00', id: A}
#   - {created: '2024-06-18T02:00:00', id: B}
        
    - debug:
        var: fp2 | to_yaml

# fp2:
#   deny:
#   - {created: '2024-06-18T02:00:00', id: C}
#   - {created: '2024-06-18T02:00:00', id: D}
#   pass:
#   - {created: '2024-06-18T02:00:00', id: A}
#   - {created: '2024-06-18T02:00:00', id: B}
