- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - community.general.xml:
        path: foo.xml
        xpath: /results/ComputerSystem
      register: result
    - debug:
        var: result
