- hosts: localhost

  vars:

    d1: {"x": "Hello", "y": "world", "contextMap": {"a": 1, "b": 2}}

    # Merge specific keys works as expected.
    #
    # You can merge the attribute contextMap with the whole
    # dictionary. But, it's not possible to get rid of the attribute
    # contextMap afterwards (see pb1.yml).

    d2: "{{ d1|json_query(d2_query) }}"
    d2_query: 'merge({"x": x}, contextMap)'

    d3: "{{ d1|json_query(d3_query) }}"
    d3_query: 'merge({"x": x}, {"y": y}, contextMap)'

  tasks:

    - debug:
        var: d2|to_nice_yaml

#  d2|to_nice_yaml: |-
#    a: 1
#    b: 2
#    x: Hello
#    y: world

    - debug:
        var: d3|to_nice_yaml

#  d3|to_nice_yaml: |-
#    a: 1
#    b: 2
#    x: Hello
#    y: world
